config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/', to: 'pages#index'
  resources :teaching_ideas
  resources :learning_dictionaries
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :users do
    member do
      get :following, :followers
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/learning_dictionary.rb
class LearningDictionary < ApplicationRecord
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/teaching_idea.rb
class TeachingIdea < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include Gravtastic
  gravtastic

  before_save { self.email = email.downcase }
  validates :username, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
            uniqueness: true

  has_many :teaching_ideas
  has_many :learning_dictionaries
  has_many :active_relationships, class_name: "Relationship",
           foreign_key: "follower_id",
           dependent: :destroy

  has_many :passive_relationships, class_name: "Relationship",
           foreign_key: "followed_id",
           dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    follwing.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to Teacher journals!"
      redirect_to @user
    else
      render 'new' end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

 helper_method :current_user
 helper_method :is_creator


 def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:username, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys:[:username, :email, :fullname ,:occupation, :age, :gender ])
 end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	render '/home/index'
  end
 
end

app/controllers/learning_dictionaries_controller.rb
class LearningDictionariesController < InheritedResources::Base

  private

    def learning_dictionary_params
      params.require(:learning_dictionary).permit(:title, :definition, :content)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    render :layout => 'home'
  end
end

app/controllers/teaching_ideas_controller.rb
class TeachingIdeasController < InheritedResources::Base

  private

    def teaching_idea_params
      params.require(:teaching_idea).permit(:title, :content)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/learning_dictionaries_helper.rb
module LearningDictionariesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teaching_ideas_helper.rb
module TeachingIdeasHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/home/index.html.erb
<h1>home</h1>

<% if current_user %>

	<%= link_to "Sign Out",destroy_user_session_path, method: :delete%>
	<%= link_to "edit Profile", edit_user_registration_path %>
	<%= link_to "teaching methods", teaching_ideas_path %>
	
	<% if current_user.is_creator? %>
	<%= link_to "create learning theories", new_learning_dictionary_path %>
	<% else %>
	<%= link_to "Learning theories", learning_dictionaries_path %>
	<%end%>

<%else%>

	<%= link_to "Sign Up",new_user_registration_path %>
	<%= link_to "Sign in",new_user_session_path %>

	<%= link_to "teaching methods", teaching_ideas_path %>
	
	<%= link_to "Learning theories", learning_dictionaries_path %>

<%end%>

app/views/home/test.html.erb
<div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
                  Orders
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
                  Products
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                  Customers
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
                  Reports
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
                  Integrations
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Saved reports</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                  Current month
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                  Last quarter
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                  Social engagement
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                  Year-end sale
                </a>
              </li>
            </ul>
          </div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
<!--    The<a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>-->
<!--    by <a href="https://www.michaelhartl.com/">Michael Hartl</a>-->
  </small>
  <nav>
    <ul>
<!--      <li><%#= link_to "About", '#' %></li>-->
<!--      <li><%#= link_to "Contact", '#' %></li>-->
<!--      <li><a href="https://news.railstutorial.org/">News</a></li>-->
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top bg-primary">
  <div class="container">
    <%= link_to "Teacher Journals", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", '#' %></li>
        <li><%= link_to "Help", '#' %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light fixed-top">
  <a class="navbar-brand text-primary">Teachers' Journals</a>
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search for teaching ideas..." aria-label="Search for teaching ideas...">
    <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeacherJournals</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teacher Journals</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <div class="container-fluid">
  <body>
  <div class="">
    <%= yield %>
  </div>
    <%= render "layouts/footer" %>
  </body>
  </div>
</html>

app/views/learning_dictionaries/_form.html.erb
<%= form_with(model: learning_dictionary, local: true) do |form| %>
  <% if learning_dictionary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(learning_dictionary.errors.count, "error") %> prohibited this learning_dictionary from being saved:</h2>

      <ul>
        <% learning_dictionary.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :definition %>
    <%= form.text_area :definition %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/learning_dictionaries/edit.html.erb
<h1>Editing Learning Dictionary</h1>

<%= render 'form', learning_dictionary: @learning_dictionary %>

<%= link_to 'Show', @learning_dictionary %> |
<%= link_to 'Back', learning_dictionaries_path %>

app/views/learning_dictionaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Learning Dictionaries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Definition</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @learning_dictionaries.each do |learning_dictionary| %>
      <tr>
        <td><%= learning_dictionary.title %></td>
        <td><%= learning_dictionary.definition %></td>
        <td><%= learning_dictionary.content %></td>
        <td><%= link_to 'Show', learning_dictionary %></td>
        <td><%= link_to 'Edit', edit_learning_dictionary_path(learning_dictionary) %></td>
        <td><%= link_to 'Destroy', learning_dictionary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Learning Dictionary', new_learning_dictionary_path %>

app/views/learning_dictionaries/new.html.erb
<h1>New Learning Dictionary</h1>

<%= render 'form', learning_dictionary: @learning_dictionary %>

<%= link_to 'Back', learning_dictionaries_path %>

app/views/learning_dictionaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @learning_dictionary.title %>
</p>

<p>
  <strong>Definition:</strong>
  <%= @learning_dictionary.definition %>
</p>

<p>
  <strong>Content:</strong>
  <%= @learning_dictionary.content %>
</p>

<%= link_to 'Edit', edit_learning_dictionary_path(@learning_dictionary) %> |
<%= link_to 'Back', learning_dictionaries_path %>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/shared/_stat.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
    <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat"> <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/static_pages/index.html.erb
<h1>
  test
</h1>

app/views/teaching_ideas/_form.html.erb
<%= form_with(model: teaching_idea, local: true) do |form| %>
  <% if teaching_idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teaching_idea.errors.count, "error") %> prohibited this teaching_idea from being saved:</h2>

      <ul>
        <% teaching_idea.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teaching_ideas/edit.html.erb
<h1>Editing Teaching Idea</h1>

<%= render 'form', teaching_idea: @teaching_idea %>

<%= link_to 'Show', @teaching_idea %> |
<%= link_to 'Back', teaching_ideas_path %>

app/views/teaching_ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teaching Ideas</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teaching_ideas.each do |teaching_idea| %>
      <tr>
        <td><%= teaching_idea.title %></td>
        <td><%= teaching_idea.content %></td>
        <td><%= link_to 'Show', teaching_idea %></td>
        <td><%= link_to 'Edit', edit_teaching_idea_path(teaching_idea) %></td>
        <td><%= link_to 'Destroy', teaching_idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teaching Idea', new_teaching_idea_path %>

app/views/teaching_ideas/new.html.erb
<h1>New Teaching Idea</h1>

<%= render 'form', teaching_idea: @teaching_idea %>

<%= link_to 'Back', teaching_ideas_path %>

app/views/teaching_ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @teaching_idea.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @teaching_idea.content %>
</p>

<%= link_to 'Edit', edit_teaching_idea_path(@teaching_idea) %> |
<%= link_to 'Back', teaching_ideas_path %>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4"> <section class="user_info">
    <h1>
      <%= gravatar_for @user %> <%= @user.username %>
    </h1> </section>
  </aside> </div>